ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    TRAINER="ShivaKumar" \
    DURATION="10HRS" \
    AUTHOR="JoinDevOps"
RUN echo "Trainer is: ${TRAINER}, version is: ${version} "
CMD ["sleep","200"]