version: "3"
services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: hemanthkumargurujupalli/mongodb:1.0.0
    container_name: mongodb
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: hemanthkumargurujupalli/redis:1.0.0
    container_name: redis
  
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile

    image: hemanthkumargurujupalli/mysql:1.0.0
    container_name: mysql
  
  

  
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: hemanthkumargurujupalli/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: hemanthkumargurujupalli/user:1.0.0
    container_name: user
    depends_on:
      - redis
  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    image: hemanthkumargurujupalli/cart:1.0.0
    container_name: cart
  shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    image: shipping:1.0.0
    container_name: hemanthkumargurujupalli/shipping
    depends_on:
      - mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hemanthkumargurujupalli/frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
    

networks:
  default:
    driver: bridge
    name: roboshop